### ISSUE TITLE
Solutions for challenges

### ISSUE THREAD

**Issue by hackerhumble** [google/firing-range#27]
Hi,

Can you please let me know where can I find the solutions for these challenges please.

**Comment by paradoxengine** [comment]
Hello,
 first, just to make sure: this is not really a test of challenges for humans. This is a testbed for automated web scanners - as such, some challenges don't even have solutions because they are meant to try to trigger false positives :-) This said, most of the test cases should be fairly straightforward and if there is anything particularly tricky ask away!
